# An Overview of wining Categories

In [1]:
import pandas as pd
import plotly.express as px
import inspect

In [19]:
df = pd.read_csv('all_categories.csv')
df.head()

,country,sku_config,product_name,main_category,sec_category,brand,selling_price,items_sold,product_link,ranking
0,KE,PE754OT12DQDYNAFAMZ,Maize Meal – 2Kg,Food cupboard,Cooking & Baking,Pembe,119,3039,https://www.jumia.co.KE/43166446.html?seller_p...,1
1,KE,SO771FF0MD80YNAFAMZ,Maize Meal - 2Kg,Food cupboard,Cooking & Baking,Soko,118,2752,https://www.jumia.co.KE/28486573.html?seller_p...,2
2,KE,ME104CP1N6B80NAFAMZ,Cream Bar Soap - 1kg,Laundry,Detergent Pacs & Tablets,Menengai,160,2552,https://www.jumia.co.KE/42819399.html?seller_p...,1
3,KE,SO771FF0MD80YNAFAMZ,Maize Meal - 2Kg,Food cupboard,Cooking & Baking,Soko,116,2062,https://www.jumia.co.KE/28486573.html?seller_p...,3
4,KE,PE754FF0395P2NAFAMZ,All Purpose Home Baking Flour - 2Kg,Food cupboard,Cooking & Baking,Pembe,143,1945,https://www.jumia.co.KE/43166450.html?seller_p...,4

In [20]:
group_df = df.groupby('main_category').sum().reset_index()
group_df.head()

,main_category,country,sku_config,product_name,sec_category,brand,selling_price,items_sold,product_link,ranking
0,Adulte,KEKEKEKE,GE840AT02HEYWNAFAMZGE840AT17ATYINAFAMZGE840AT0...,Vibrator Female Dildo G Spot StimulatorRealist...,adulteadulteadulteadulte,GenericGenericGenericGeneric,4930,91,https://www.jumia.co.KE/48717140.html?seller_p...,10
1,Appliances,KEKEKEKEKEKEKEKEKEKEKEKEKEKEKEKEKEKEKEKEKEKEKE...,AN944HA0FHI99NAFAMZAN944HA0FHI99NAFAMZBM953HA0...,2L Electric Automatic Kettle + 1 Spoon 1 Fork....,Small ApplianceSmall ApplianceSmall ApplianceS...,AnnovAnnovBM SATELLITERashnikAnnovElegantGener...,260618,4282,https://www.jumia.co.KE/35011062.html?seller_p...,3327
2,Automotive & Motorcycles,KEKEKEKEKEKEKEKEKEKEKE,GE840CA0SS16GNAFAMZGE840EA0VIADLNAFAMZGE840CA0...,See Through Digital Car Insurance Display Pock...,AutomotiveAutomotiveAutomotiveAutomotiveAutomo...,GenericGenericGenericGeneric9h Mr FixToyotaGen...,11296,402,https://www.jumia.co.KE/44173384.html?seller_p...,66
3,Beauty & perfumes,KEKEKEKEKEKEKEKEKEKEKEKEKEKEKEKEKEKEKEKEKEKEKE...,DR647ST1CHVZQNAFAMZGA297ST0P1A0HNAFAMZGA297HB0...,Vitamin C Brightening & Anti-Aging Face Serum ...,Facial skincareFacial skincareFacial skincareF...,Dr. RashelGARNIERGARNIERGARNIERGARNIERGARNIERG...,360684,26598,https://www.jumia.co.KE/28165418.html?seller_p...,34912
4,Beverages,KEKEKEKE,NE683DR1CBK7INAFAMZFR155DB05868BNAFAMZFL593DB0...,Classic Jar 100gOrange Juice 250mlORIGINAL Her...,Tea and CoffeeJuicesTea and CoffeeTea and Coffee,NESCAFEFruitvilleFlat tummy teaFlat tummy tea,2193,89,https://www.jumia.co.KE/47906118.html?seller_p...,7

In [23]:
tt_products = pd.DataFrame(df['main_category'].value_counts()).reset_index()
tt_products.columns = ['main_category', 'tt_products']
tt_products

               main_category  tt_products
0          Beauty & perfumes          630
1              Food cupboard          547
2                     Phones          286
3                       Home          236
4       TVs, Audio and Video          191
5             Household care          165
6                  Computing          160
7        Women's accessories          156
8                 Appliances           97
9          Men's accessories           93
10            Men's clothing           85
11               Men's shoes           63
12          Women's clothing           62
13                   Laundry           54
14             Women's shoes           41
15             Kids and Baby           37
16     Cameras & Accessories           16
17           Sport & Fitness           15
18      Unisex's accessories           15
19  Automotive & Motorcycles           11
20                      Boys            8
21     Tablets & Accessories            6
22                   Fashion            4
23                   Tobacco            4
24                 Beverages            4
25                    Adulte            4
26          Games & Consoles            3
27        Books & Stationery            3
28       Musical Instruments            2
29                     Girls            1

In [40]:
avgdf = group_df[['main_category','selling_price','items_sold']]
avgdf = avgdf.merge(tt_products)
avgdf.columns = ['main_category', 'tt_selling_price', 'items_sold', 'tt_products']

avgdf['avg_selling_price'] = (avgdf['tt_selling_price']/avgdf['tt_products']).astype(int)
avgdf['avg_products_sold'] = (avgdf['items_sold']/avgdf['tt_products']).astype(int)
avgdf['avg_revenue'] = (avgdf['avg_products_sold'] * avgdf['avg_selling_price'])
avgdf['20%_profit'] = (avgdf['avg_revenue'] * 0.2).astype(int)

avgdf = avgdf.sort_values('20%_profit', ascending=False).reset_index(drop=True)

In [41]:
avgdf

,main_category,tt_selling_price,items_sold,tt_products,avg_selling_price,avg_products_sold,avg_revenue,20%_profit
0,Phones,1679547,10907,286,5872,38,223136,44627
1,"TVs, Audio and Video",861944,6913,191,4512,36,162432,32486
2,Appliances,260618,4282,97,2686,44,118184,23636
3,Tablets & Accessories,20068,157,6,3344,26,86944,17388
4,Computing,224813,6684,160,1405,41,57605,11521
5,Games & Consoles,8377,60,3,2792,20,55840,11168
6,Food cupboard,227382,60340,547,415,110,45650,9130
7,Unisex's accessories,14720,688,15,981,45,44145,8829
8,Laundry,17768,6546,54,329,121,39809,7961
9,Home,319151,6869,236,1352,29,39208,7841
10,Automotive & Motorcycles,11296,402,11,1026,36,36936,7387
11,Men's clothing,67276,3705,85,791,43,34013,6802
12,Cameras & Accessories,22456,344,16,1403,21,29463,5892
13,Women's clothing,34422,3173,62,555,51,28305,5661
14,Adulte,4930,91,4,1232,22,27104,5420
15,Men's shoes,61153,1721,63,970,27,26190,5238
16,Tobacco,3164,128,4,791,32,25312,5062
17,Beauty & perfumes,360684,26598,630,572,42,24024,4804
18,Women's accessories,92794,6192,156,594,39,23166,4633
19,Men's accessories,46352,3930,93,498,42,20916,4183
20,Sport & Fitness,12347,372,15,823,24,19752,3950
21,Kids and Baby,25972,1066,37,701,28,19628,3925
22,Women's shoes,21869,1276,41,533,31,16523,3304
23,Boys,5202,176,8,650,22,14300,2860
24,Household care,49333,7739,165,298,46,13708,2741
25,Fashion,2000,109,4,500,27,13500,2700
26,Books & Stationery,2450,47,3,816,15,12240,2448
27,Beverages,2193,89,4,548,22,12056,2411
28,Girls,279,17,1,279,17,4743,948
29,Musical Instruments,419,35,2,209,17,3553,710

In [42]:
avgdf.to_csv('main_category_analysis.csv', index=False)